name: Step Types

on: workflow_dispatch

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - name: Run inline bash
        run: echo "Hello from an inline bash script in a GitHub Action Workflow!"

  say-hello-python-bash:
    runs-on: ubuntu-24.04
    steps:
      - name: Run inline python
        shell: python
        run: print("Hello from an inline script in a GitHub Action Workflow!")

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - name: Run marketplace action
        uses: actions/hello-world-javascript-action@v1