name: Level 1 Basic
on: workflow_dispatch

env:
  USER_NAME: "Anish" # Hardcoded at the top

jobs:
  say-hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Greet User
        run: echo "Hello, $USER_NAME!"